spring:
  profiles:
    active: dev

# ローカル環境
---
spring:
  profiles: dev
  data:
    basePath: /api
  datasource:
    url: jdbc:mysql://localhost:3306/girls_band_party_profile?useSSL=false
    username: root
    password: catty229
    driverClassName: com.mysql.jdbc.Driver

# テスト環境
---
spring:
  profiles: test
  data:
    basePath: /api
  datasource:
    url: jdbc:mysql://[テスト環境のアクセス情報]
    username: [ユーザ名]
    password: [パスワード]
    initialize: com.mysql.jdbc.Driver

# 本番環境
---
spring:
  profiles: production
  data:
    basePath: /api
  datasource:
    url: jdbc:mysql://[本番環境のアクセス情報]
    username: [ユーザ名]
    password: [パスワード]
    initialize: com.mysql.jdbc.Driver

jpa:
  database: MYSQL
  hibernate:
    ddl-auto: update
    show-sql: true
